name: 'CircuitPython Library CI Tips'
description: 'Provides a single comment to the given PR with tips about fixing the CircuitPython library CI'
inputs:
  token:
    description: 'Token to use to post the comment'
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "index.js"
